name: Deploying terraform code to AWS

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DEPLOY to confirm"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    concurrency:
      group: terraform
      cancel-in-progress: false

    timeout-minutes: 15

    defaults:
      run:
        working-directory: infra

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug repo structure
        run: ls -R

      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "DEPLOY" ]; then
            echo "Confirmation failed. Exiting."
            exit 1
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::337170977317:role/TerraformResourceAccess
          aws-region: eu-west-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt check
        run: terraform fmt -check

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --config .tflint.hcl

      - name: Terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan -lock=false 


      - name: Terraform apply (with SHA)
        run: terraform apply --auto-approve -var="image_tag=${{ github.sha }}"