name: Deploy Terraform to AWS

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  TF_VAR_image_uri: ${{ secrets.IMAGE_URI }}
  TF_VAR_image_tag: ${{ github.event.workflow_run.head_sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: terraform
      cancel-in-progress: false

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TERRAFORM_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.15.3

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Run Checkov Terraform Scan
        uses: bridgecrewio/checkov-action@master
        with:
         directory: ./infra
         framework: terraform

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve