name: Deploying terraform code to AWS

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DEPLOY to confirm"
        required: true

permissions:
  id-token: write
  contents: read

env: 
  AWS_REGION: eu-west-2
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  TF_VAR_image_uri: ${{ secrets.IMAGE_URI }}
  TF_VAR_VPC_CIDR: ${{ secrets.VPC_CIDR }}
  TF_VAR_VPC_CIDR_PRIVATE1: ${{ secrets.VPC_CIDR_PRIVATE1 }}
  TF_VAR_VPC_CIDR_PRIVATE2: ${{ secrets.VPC_CIDR_PRIVATE2 }}
  TF_VAR_VPC_CIDR_PUBLIC1: ${{ secrets.VPC_CIDR_PUBLIC1 }}
  TF_VAR_VPC_CIDR_PUBLIC2: ${{ secrets.VPC_CIDR_PUBLIC2 }}
  TF_VAR_ecs_cpu: "512"
  TF_VAR_ecs_memory: "1024"
  TF_VAR_container_port: 3000
  TF_VAR_host_port: 3000
  TF_VAR_domain_name: "ecs.abdishakurosman.uk"
  TF_VAR_image_tag: ${{ github.sha }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    concurrency:
      group: terraform
      cancel-in-progress: false

    timeout-minutes: 15

    defaults:
      run:
        working-directory: infra

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug repo structure
        run: ls -R

      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "DEPLOY" ]; then
            echo "Confirmation failed. Exiting."
            exit 1
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TERRAFORM_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt check
        run: terraform fmt -check

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --config .tflint.hcl

      - name: Terraform validate
        run: terraform validate


      - name: Debug TF_VAR injection
        run: |
         echo "TOKEN LENGTH:"
         echo "${TF_VAR_cloudflare_api_token}" | wc -c
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: terraform plan
        run: terraform plan -lock=false 


      - name: Terraform apply (with SHA)
        run: terraform apply --auto-approve